### Questão 1

In [4]:
import pandas as pd

seriesAno1 = pd.Series({'Java': 16.25, 'C': 16.04, 'Python': 9.85})
seriesAno2 = pd.Series({'C': 16.21, 'Python': 12.12, 'Java': 11.68})

### Questão 2

In [5]:
print(seriesAno1.sum())
print(seriesAno2.sum())

42.14
40.01

### Questão 3

In [6]:
crescimento = seriesAno2 - seriesAno1
crescimento

C         0.17
Java     -4.57
Python    2.27
dtype: float64

### Questão 4

In [7]:
crescimento[crescimento > 0]

C         0.17
Python    2.27
dtype: float64

### Questão 5

In [8]:
futuro = seriesAno2 + 2 * crescimento
futuro.nlargest(1)

Python    16.66
dtype: float64

### Questão 6

In [9]:
import numpy as np

df = pd.DataFrame(
    index=['A', 'B', 'C', 'D', 'E'],
    columns=['W', 'X', 'Y', 'Z'],
    data=np.random.randint(1, 50, [5, 4])
)
df

    W   X   Y   Z
A  19  12  34   1
B  13   4  23   3
C   8  16  13  34
D   7  21  21  16
E  19  24   8  29

In [10]:
df.loc[df['X'] < 30, 'X'].mean()

np.float64(15.4)

### Questão 7

In [11]:
print(df.loc['D'].mean())
print(df.iloc[4].sum())

16.25
80

### Questão 8

In [12]:
subset = df.loc[['A', 'C', 'E'], ['X', 'Y']]
subset

    X   Y
A  12  34
C  16  13
E  24   8

In [13]:
print(subset.sum(axis=1))
print(subset.sum(axis=0))

A    46
C    29
E    32
dtype: int64
X    52
Y    55
dtype: int64